services:
- type: web
  name: tech-blog
  env: node
  plan: free
  buildCommand: 'npm install'
  startCommand: 'npm start'
  envVars:
    - key: DB_NAME
      value: your_db_name
    - key: DB_USER
      value: your_db_user
    - key: DB_PASSWORD
      value: your_db_password
    - key: DB_HOST
      value: your_db_host
    - key: DB_PORT
      value: 5432
    - key: SESSION_SECRET
      value: your_secret
